/**
 * Regenerates client.terminal.js — the lazy chunk carrying the vendored xterm
 * renderer and the screen component.
 *
 * The browser module loader serves a package-local chunk (`client.<name>.js`,
 * requested with `require.async('./client.<name>.js')`) as one self-contained
 * classic script, so the vendored UMD bundles are concatenated here instead of
 * being resolved at run time. Run: node build.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

/**
 * Wrap a vendored UMD bundle so its `module`/`exports` probes resolve to a
 * local object instead of the chunk's own exports.
 * @param source - the UMD text.
 * @returns an IIFE expression evaluating to the bundle's namespace.
 */
const umd = (source) =>
  `(function () {\n\tvar module = { exports: {} };\n\tvar exports = module.exports;\n${source}\n\treturn module.exports;\n})()`;

const out = `/**
 * Generated by build.mjs — do not edit. Vendors @xterm/xterm 6.0.0 and
 * @xterm/addon-fit 0.11.0 (MIT) plus src/terminal-screen.js.
 */
window.__ModuleLoader__.load({
\tid: '@wasp/dsh-terminal-dock',
\tchunk: 'client.terminal.js',
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tconst React = require('react');
\t\tconst h = React.createElement;
\t\t/** xterm.css travels with the renderer so one request carries everything. */
\t\tconst XTERM_CSS = ${JSON.stringify(read('./vendor/xterm.css'))};
\t\tconst XTERM = ${umd(read('./vendor/xterm.js'))};
\t\tconst FIT = ${umd(read('./vendor/addon-fit.js'))};
${read('./src/terminal-screen.js')}
\t\texports.TerminalScreen = TerminalScreen;
\t\treturn module.exports;
\t},
});
`;

writeFileSync(new URL('./client.terminal.js', import.meta.url), out);
console.log(`client.terminal.js written: ${out.length} bytes`);
